CREATE DATABASE IF NOT EXISTS golbat CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS reactmap CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON golbat.* TO 'pogo'@'%';
GRANT ALL PRIVILEGES ON reactmap.* TO 'pogo'@'%';
FLUSH PRIVILEGES;
