port = 9001
raw_bearer = "${GOLBAT_RAW_BEARER}"
api_secret = "${GOLBAT_API_SECRET}"
api_docs = true

[database]
username = "${DB_USER}"
password = "${DB_PASSWORD}"
address = "mariadb:3306"
db = "golbat"

[koji]
url = "http://koji:8080/api/v1/geofence/feature-collection/default"
bearer_token = "${KOJI_BEARER_TOKEN}"

[[webhooks]]
url = "http://poracle:3030"
